Fiap.DesenvolvimentoWeb.CadastroEventos/Controllers/ConvidadosController.cs
using Fiap.DesenvolvimentoWeb.CadastroEventos.DAL;
using Fiap.DesenvolvimentoWeb.CadastroEventos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.DesenvolvimentoWeb.CadastroEventos.Controllers
{
    public class ConvidadosController : Controller
    {
        [HttpGet]
        public ActionResult Cadastro()
        {
            ViewBag.ListaEventos = new SelectList(EventosDb.ListarEventos(), "IDEvento", "Descricao");
            return View();
        }

        [HttpPost]
        public ActionResult Cadastro(TBConvidados conv)
        {
            if (ModelState.IsValid)
            {
                EventosDb.IncluirConvidado(conv);
                return RedirectToAction("Index", "Home");
            }

            ViewBag.ListaEventos = new SelectList(EventosDb.ListarEventos(), "IDEvento", "Descricao");
            return View();
        }

        [HttpGet]
        public ActionResult ListarConvidados(int? idEvento)
        {
            ViewBag.TodosEventos = new SelectList(EventosDb.ListarEventos(), "IDEvento", "Descricao");
            return View(EventosDb.ListarConvidados(idEvento));
        }
    }
}

Fiap.DesenvolvimentoWeb.CadastroEventos/Views/Convidados/Cadastro.cshtml
@model Fiap.DesenvolvimentoWeb.CadastroEventos.Models.TBConvidados

@{
    ViewBag.Title = "Cadastro";
}

<h2>Cadastro</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TBConvidados</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IDEvento, "Eventos", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDEvento", (SelectList)@ViewBag.ListaEventos, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDEvento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Convidado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Convidado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Convidado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastro" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", "Home")
</div>

Fiap.DesenvolvimentoWeb.CadastroEventos/Views/Convidados/ListarConvidador.cshtml
@model IEnumerable<Fiap.DesenvolvimentoWeb.CadastroEventos.Models.TBConvidados>

@{
    ViewBag.Title = "ListarConvidador";
}

<h2>ListarConvidador</h2>

<p>
    @using (Html.BeginForm("ListarConvidador", "Convidados", FormMethod.Get))
    {
        @Html.Label("Selecionar evento:")
        @Html.DropDownList("idEvento", (SelectList)@ViewBag.TodosEventos, "Todos")
        <input type="submit" value="Mostrar Convidados" class="btn btn-default" />
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Convidado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TBEventos.Descricao)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Convidado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.TBEventos.Descricao)*@
                @Html.DisplayFor(modelItem => item.IDEvento)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.IDConvidado }) |
                @Html.ActionLink("Details", "Details", new { id = item.IDConvidado }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.IDConvidado })
            </td>
        </tr>
    }

</table>

Fiap.DesenvolvimentoWeb.CadastroEventos/Views/Convidados/ListarConvidados.cshtml
@model IEnumerable<Fiap.DesenvolvimentoWeb.CadastroEventos.Models.TBConvidados>

@{
    ViewBag.Title = "ListarConvidados";
}

<h2>ListarConvidados</h2>

<p>
    @using (Html.BeginForm("ListarConvidados", "Convidados", FormMethod.Get))
    {
        @Html.Label("Selecionar evento:")
        @Html.DropDownList("idEvento", (SelectList)@ViewBag.TodosEventos, "Todos")
        <input type="submit" value="Mostrar Convidados" class="btn btn-default" />
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Convidado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TBEventos.Descricao)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Convidado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.TBEventos.Descricao)*@
                @Html.DisplayFor(modelItem => item.IDEvento)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.IDConvidado }) |
                @Html.ActionLink("Details", "Details", new { id = item.IDConvidado }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.IDConvidado })
            </td>
        </tr>
    }

</table>