Fiap.DesenvolvimentoWeb.CadastroEventos/Controllers/AutenticacaoController.cs
using Fiap.DesenvolvimentoWeb.CadastroEventos.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.DesenvolvimentoWeb.CadastroEventos.Controllers
{
    public class AutenticacaoController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Usuario usuario, string ReturnUrl)
        {
            if (!ModelState.IsValid)
                return View();

            var usuarioStore = new UserStore<IdentityUser>();
            var usuarioManager = new UserManager<IdentityUser>(usuarioStore);
            var usuarioInfo = usuarioManager.Find(usuario.Nome, usuario.Senha);

            if (usuarioInfo == null)
            {
                ViewBag.Erro = "Usuário ou senha inválidos";
                return View();
            }

            var autManager = System.Web.HttpContext.Current.GetOwinContext().Authentication;
            var identidadeUsuario = usuarioManager.CreateIdentity(usuarioInfo,
                DefaultAuthenticationTypes.ApplicationCookie);

            autManager.SignIn(new AuthenticationProperties()
            {
                IsPersistent = false
            },
            identidadeUsuario);

            if (string.IsNullOrEmpty(ReturnUrl))
                return RedirectToAction("Index", "Home");

            return Redirect(ReturnUrl);
        }

        [HttpGet]
        public ActionResult Logout()
        {
            var autManager = System.Web.HttpContext.Current.GetOwinContext().Authentication;
            autManager.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Criar(Usuario usuario)
        {
            if (!ModelState.IsValid)
                return View();

            var usuarioStore = new UserStore<IdentityUser>();
            var usuarioManager = new UserManager<IdentityUser>(usuarioStore);

            //Cria uma identidade
            var usuarioInfo = new IdentityUser()
            {
                UserName = usuario.Nome
            };

            //Cria o usuário
            IdentityResult resultado = usuarioManager.Create(usuarioInfo, usuario.Senha);

            //se o usuário foi criado, o autentica
            if (resultado.Succeeded)
            {
                //Autentica e volta para a página inicial
                var autManager = System.Web.HttpContext.Current.GetOwinContext().Authentication;
                var identidadeUsuario = usuarioManager.CreateIdentity(usuarioInfo,
                    DefaultAuthenticationTypes.ApplicationCookie);
                autManager.SignIn(new AuthenticationProperties() { }, identidadeUsuario);

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Erro = resultado.Errors.FirstOrDefault();
                return View();
            }
        }
    }
}

Fiap.DesenvolvimentoWeb.CadastroEventos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Eventos FIAP</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Eventos FIAP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">                </ul>
                @{ Html.RenderPartial("_UsuarioPV");}
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Eventos FIAP</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Fiap.DesenvolvimentoWeb.CadastroEventos/Views/Shared/_UsuarioPV.cshtml
@if (Request.IsAuthenticated)
{
    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink(User.Identity.Name, "Index", "Autenticacao")</li>
        <li>@Html.ActionLink("Log Out", "Logout", "Autenticacao")</li>
    </ul>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Cadastrar-se", "Criar", "Autenticacao")</li>
        <li>@Html.ActionLink("Log In", "Login", "Autenticacao")</li>
    </ul>
}